package jpdgoncalves.iotdatasim.base;

/**
 * Classes implementing this interface represent
 * a simulator for some particular kind of sensor
 * capable of making measurement of the real world
 * like temperature or humidity.
 * @param <T> The type of data that the sensor will produce
 */
public interface SensorSimulator<T> {

    /**
     * Read the latest value generated by the
     * sensor.
     * @return The generated value.
     */
    public T readValue();

    /**
     * Ticks the sensor simulator. How much
     * time each tick represents is up to
     * the user.
     * @throws SimulationEndedException Use to indicate the simulation
     * of this sensor has reached its conclusion.
     */
    public void tick() throws SimulationEndedException;
}